name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{secrets.VERCEL_PROJECT_ID}}

on:
  push:
    branches:
      - "staging"

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{secrets.VERCEL_TOKEN}}

      - name: Build Project Artifacts
        run: vercel build --token=${{secrets.VERCEL_TOKEN}}

      - name: Assign beta domain
        run: |
          vercel deploy --prebuilt --token=${{secrets.VERCEL_TOKEN}} > domain.txt
          vercel alias set `cat domain.txt` staging-test-vercel-livid-beta-17.vercel.app --scope ${{secrets.VERCEL_ORG_ID}} --token ${{secrets.VERCEL_TOKEN}}
