name: Vercel Preview Deployment (Next Test)

on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 4" # 목요일 오전 9시

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_NEXT_TEST }}

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: staging

      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-test-build
          path: .vercel/output
          retention-days: 1

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    environment:
      name: Preview
      url: https://staging-next-test-six-theta-58.vercel.app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install PNPM
        with:
          run_install: false

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Download Build Artifacts
        uses: actions/download-artifact@v4
        with:
          name: next-test-build
          path: app/next-test/.vercel/output

      - name: Pull Vercel Environment Information
        working-directory: app/next-test
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        working-directory: app/next-test
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} > domain.txt
          vercel alias set `cat domain.txt` staging-next-test-six-theta-58.vercel.app --scope ${{ secrets.VERCEL_ORG_ID }} --token ${{ secrets.VERCEL_TOKEN }}
